bindAddr = "0.0.0.0"
bindPort = 5443
kcpBindPort = 5443

vhostHTTPPort = 5000
vhostHTTPSPort = 5001

transport.maxPoolCount = 2000
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
transport.tls.force = false

webServer.addr = "0.0.0.0"
webServer.port = 6443
webServer.user = "admin"
webServer.password = "admin123"
webServer.pprofEnable = false

log.to = "./frps.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false

auth.method = "token"
auth.token = "jknxsxHBFp1KLW38"

maxPortsPerClient = 5

allowPorts = [
  { start = 10000, end = 65535 }
]

udpPacketSize = 1500
natholeAnalysisDataReserveHours = 168
