bindAddr = "0.0.0.0"
bindPort = 5443
kcpBindPort = 5443

vhostHTTPPort = 5444
vhostHTTPSPort = 5445


webServer.addr = "0.0.0.0"
webServer.port = 6443
webServer.user = "admin"
webServer.password = "admin123"
webServer.pprofEnable = false

log.to = "./frps.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false
enablePrometheus = true

auth.method = "token"
auth.token = "jknxsxHBFp1KLW39"

maxPortsPerClient = 5

allowPorts = [
  { start = 1, end = 65535 }
]

